### PR TITLE
Fix fields of first article when running init

### LINKED ISSUE #282: 初始化时，第一篇文章（默认）的字段问题
**简要描述 Bug**
通过 `tuture init` 初始化后，第一篇文章的字段存在问题：1）`id` 字段应该和文集 `id` 不一样；2）缺少 `created`、`topics` 等其他字段。

**Tuture 版本信息**
开发版。

**详细的报错调用栈信息**
无。

**复现步骤**
复现 Bug 的完整步骤：

1. 进入一个 Git 仓库
2. 运行 `tuture init`
3. `collection.json` 中的第一篇文章字段有问题

**期望的行为逻辑**
第一篇文章的字段应该类似这样：

```json
{
    "id": "8b0e4824",
    "created": "2020-05-04T13:44:46.498Z",
    "name": "第一篇",
    "topics": [],
    "categories": [],
    "cover": ""
  }
```

**屏幕截图**
出错时的屏幕截图（有 GIF 的话就更棒啦！）

### PR DESCRIPTION
**Pull request by mRcfps**
Closes #282.

### CODE REVIEW

File: packages/cli/src/commands/init.ts [hunk 1]
```diff
@@ -81,15 +78,26 @@ export default class Init extends BaseCommand {
...
         created: new Date(),
-        articles: [meta],
+        articles: [
+          {
+            id: defaultArticleId,
+            name: meta.name,
+            topics: [],
+            categories: [],
+            created: new Date(),
+            cover: '',
```
Comment (pftom) [inline packages/cli/src/commands/init.ts:98]: 是不是漏掉了 description
