### PR TITLE
Fix issues after tsify

### LINKED ISSUE #215: Cannot add link with hotkey and click toolbutton
**Describe the bug**

**To Reproduce**

**Expected behavior**
Can insert link with hotkey or click link toolbutton

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mRcfps**
Closes #215, #219 and #220.

Note that `insertLink` and `updateLink` is still broken in editure. I'll fix it today.

### CODE REVIEW

File: editor/src/components/ConnectedLayout/ChildrenDrawerComponent/CreateEditArticle.tsx [hunk 1]
```diff
@@ -98,22 +106,20 @@ function CreateEditArticle(props: CreateEditArticleProps) {
...
+    ...getArtcleMetaById(step.articleId || '', articles),
+  }));
 
   // prettier-ignore
   useEffect(() => {
     if (collectionSteps) {
       setCollectionStepsState(collectionSteps);
     }
-  }, [collection]);
+  }, [collection, collectionSteps]);
```
Comment (mRcfps) [inline editor/src/components/ConnectedLayout/ChildrenDrawerComponent/CreateEditArticle.tsx:122]: Oh no. Another sh*t caused by ESLint autofix.

**Comment by pftom** [comment]
@mRcfps Click list-item toolbutton still throw error

**Comment by pftom** [comment]
@mRcfps
